"""empty message

Revision ID: 59470f7bd312
Revises: 
Create Date: 2018-02-14 01:07:43.675259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59470f7bd312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('M_CONFIG',
    sa.Column('KEY', sa.String(), nullable=False),
    sa.Column('VALUE', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('KEY')
    )
    op.create_table('M_PROXY_POINT',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('DES_DEVICE_ID', sa.Integer(), nullable=True),
    sa.Column('DES_OBJECT_ID', sa.Integer(), nullable=True),
    sa.Column('DES_INSTANCE_ID', sa.Integer(), nullable=True),
    sa.Column('DES_PROPERTY_ID', sa.Integer(), nullable=True),
    sa.Column('SRC_DEVICE_ID', sa.Integer(), nullable=True),
    sa.Column('SRC_OBJECT_ID', sa.Integer(), nullable=True),
    sa.Column('SRC_INSTANCE_ID', sa.Integer(), nullable=True),
    sa.Column('SRC_PROPERTY_ID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('M_PROXY_POINT')
    op.drop_table('M_CONFIG')
    # ### end Alembic commands ###
