"""empty message

Revision ID: 6b42cbf5d86a
Revises: 31ec7f5fea3c
Create Date: 2018-05-15 17:57:36.932003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b42cbf5d86a'
down_revision = '31ec7f5fea3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('M_BACNET_SIMULATION_PROPERTY', sa.Column('TYPE', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('M_BACNET_SIMULATION_PROPERTY', 'TYPE')
    # ### end Alembic commands ###
