"""empty message

Revision ID: b157d6c6cef4
Revises: 
Create Date: 2018-03-13 10:15:31.198339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b157d6c6cef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('M_BACNET_EMULATION_OBJECT',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(), nullable=True),
    sa.Column('OBJECT_ID', sa.Integer(), nullable=True),
    sa.Column('INSTACNE_ID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('M_CONFIG',
    sa.Column('KEY', sa.String(), nullable=False),
    sa.Column('VALUE', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('KEY')
    )
    op.create_table('M_PROXY_POINT',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('DES_DEVICE_ID', sa.Integer(), nullable=True),
    sa.Column('DES_OBJECT_ID', sa.Integer(), nullable=True),
    sa.Column('DES_INSTANCE_ID', sa.Integer(), nullable=True),
    sa.Column('DES_PROPERTY_ID', sa.Integer(), nullable=True),
    sa.Column('SRC_DEVICE_ID', sa.Integer(), nullable=True),
    sa.Column('SRC_OBJECT_ID', sa.Integer(), nullable=True),
    sa.Column('SRC_INSTANCE_ID', sa.Integer(), nullable=True),
    sa.Column('SRC_PROPERTY_ID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('M_BACNET_EMULATION_PROPERTY',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('PROPERTY_ID', sa.Integer(), nullable=True),
    sa.Column('M_EMULATION_POINT_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['M_EMULATION_POINT_ID'], ['M_BACNET_EMULATION_OBJECT.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('M_BACNET_EMULATION_PROPERTY')
    op.drop_table('M_PROXY_POINT')
    op.drop_table('M_CONFIG')
    op.drop_table('M_BACNET_EMULATION_OBJECT')
    # ### end Alembic commands ###
