"""empty message

Revision ID: bf3a4bbb8993
Revises: 
Create Date: 2018-01-27 21:40:45.753502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3a4bbb8993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('M_CONFIG',
    sa.Column('KEY', sa.String(), nullable=False),
    sa.Column('VALUE', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('KEY')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('M_CONFIG')
    # ### end Alembic commands ###
