"""empty message

Revision ID: e3d7d88488c5
Revises: b157d6c6cef4
Create Date: 2018-03-15 14:23:09.629955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d7d88488c5'
down_revision = 'b157d6c6cef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('M_TASK_GROUP',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(), nullable=True),
    sa.Column('INTERVAL', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('M_TASK_GROUP')
    # ### end Alembic commands ###
